### ISSUE TITLE
[KK] CharaMaker now pauses for a minute or two when first loading (v1.2.1-v1.2.1.5).

### ISSUE THREAD

**Issue by Jatts-Art** [Prolo1/Character-Morpher#16] opened 2024-06-02 05:00 UTC
This did not happen on the previous version I was using for many months, v1.1.0, and today I've updated to v1.2.1.5.

Now the "Chara" checkboxes reset everytime I start CharMaker, in addition to a 1-2 minute hangtime as well. Majority of these checkboxes I still don't understand what they do anyway, due to lack of guidelines for this plugin, so I often prefer to keep them off as they have always seemed redundant and I never needed to use them.

However, I also tested v1.2.0 and that one doesn't have the extra loading times... while v1.2.1-v1.2.1.5 does. The UI before v1.2.1 is more preferable looking too, in my opinion.

For now I will likely stick with v1.2.0, the extra loading times is too annoying otherwise.

**Comment by Prolo1** [comment] 2024-06-07 11:36
Thanks for the report.
In terms of the toggle names, I'm adding tooltips to clarify what each of them does (hopefully). I may also change some names entirely if I can find better ones.

The "chara" toggles being reset was probably a result of my testing that when cards are saved with my data in them they properly overwrite the current "chara" toggles. I'll stop the reset and add a load toggle to optionally disable the overwrite by the next update.

As for the load times, I have no idea why from 1.2.0 -> 1.2.1 there is ANY load time change since I hardly changed anything (unless you meant 1.1.0 ->1.2.1). There is one small change I can make that could be the reason but other than that ¯\_(ツ)_/¯.

**Comment by Prolo1** [comment] 2024-06-07 11:37
If I make a test build, I'll put a link to it in here.

**Comment by Jatts-Art** [comment] 2024-06-08 13:15
Sure! Sounds good

**Comment by Prolo1** [comment] 2024-06-12 12:17
Here's a test build (couldn't test it on KK since I've misplaced my drive with the game on it. I did at least test on KKS with no issues). give this a shot. 
https://github.com/Prolo1/Character-Morpher/releases/tag/Test

**Comment by Jatts-Art** [comment] 2024-06-12 17:09
Tested it just now, and the loading delay at the start still exists.... The UI is improved, however it also changed the character loading menu as well!

![46e4128fda670d7f55c9c5536d8f2b92](https://github.com/Prolo1/Character-Morpher/assets/12752293/20a7a2e4-b63f-442d-9737-e51e7b58e3de)

**Comment by Prolo1** [comment] 2024-06-12 23:02
That's kinda weird (That does not happen in the other games for me). I'm starting to think the load issue may just be your computer but I want to test on KK specifically to make sure. Good news is I finally found my drive, that said I still need to update the game since it's been a while.

I think there is a mod or vanilla setting that changes the number of cards per row but don't quote me on that (I have no control over that at all, that's just how the game decided to handle **ONE** extra load toggle and only in that game ¯\\_(ツ)_/¯). 

It may also help if you send me the log file for the game and how much RAM you got.

**Comment by Jatts-Art** [comment] 2024-06-13 03:02
Literally not a single time have I had issues with this game, and I have 64gb of ram. Ain't my PC mate.

**Comment by Prolo1** [comment] 2024-06-13 04:47
just checked with KK and ya the hangup does happen but I doubt it's my character loading since that is the code that has gone unchanged for about a year now (if that went slow It would show on every platform). That said as I'm writing this I have found where the hangup happens and it's kinda absurd. 

https://github.com/Prolo1/Character-Morpher/blob/cfa41bcf74064c480783aa12ebb902696b58de7d/Common/CharaMorpher.cs#L2117

For some reason, that line of code that by design should allow for other code to run regardless of if the function is finished or not just stops there for no reason and only in this game. I'll see if removing it removes the lag and if it does then ¯\\_(ツ)_/¯ issues gone.

**Comment by Jatts-Art** [comment] 2024-06-13 04:50
sorry, something came up. but i'll test again to get that output log if you still need it

**Comment by Prolo1** [comment] 2024-06-13 05:04
Ya I've heard similar as well, and it seems to be concentrated in KK since it's using a fairly older version of Unity. I've also tested my theory and I can confirm that that line caused it 🤣.

**Comment by Prolo1** [comment] 2024-06-13 05:05
I still need it tho since it allows me to actually check if an object I need exists.

**Comment by Jatts-Art** [comment] 2024-06-13 05:05
Here is my output log anyway.

[output_log.txt](https://github.com/user-attachments/files/15813986/output_log.txt)

Also I just now had another friend of mine test, just in case, and yeah it hung up for him too... although he did not have the UI issue that I did, so that could be a plugin conflict that I would need to track down perhaps.

**Comment by Israfelim** [comment] 2024-06-13 05:06
I've had the hang-up happen as well on my end, seems to be 30-45 seconds and then it's fine on initial startup, but no weirdness with the card menu.

**Comment by Prolo1** [comment] 2024-06-13 05:07
THe card menu thing never happened for me either

**Comment by Jatts-Art** [comment] 2024-06-18 04:33
bruh

**Comment by Prolo1** [comment] 2024-06-19 01:46
After beating my head against a wall for a few days, I fixed the issue with loading (there were a couple of other locations that also slowed down code). shouldn't have taken as long as it did but IRL stuff got in the way. so here is another build.

https://github.com/Prolo1/Character-Morpher/releases/tag/Test5

**Comment by Prolo1** [comment] 2024-06-19 01:48
let me know if it works better for you guys too

**Comment by Jatts-Art** [comment] 2024-06-20 17:02
very sorry, was busy the other day but I can test this in an hour or so!

**Comment by Jatts-Art** [comment] 2024-06-20 17:55
> After beating my head against a wall for a few days, I fixed the issue with loading (there were a couple of other locations that also slowed down code). shouldn't have taken as long as it did but IRL stuff got in the way. so here is another build.
> 
> https://github.com/Prolo1/Character-Morpher/releases/tag/Test5

Okay so after doing quick testing, I can finally say that the pausing issue has stopped. Thank you very much for taking the time to do that!

The UI also seems better, although the character card window itself still seems weird but since that issue did not happen for my friend I will assume its from some sort of other plugin conflict... I will look into that later.

Lastly, after doing quick morph tests, I should mention a bug i found. When using the blue percentage buttons, the displayed numbers will not update properly on any sliders. I can still tell that its the correct data, judging by the results, but the actual number seen does not seem to refresh itself properly.

**Comment by Prolo1** [comment] 2024-06-20 23:01
Let's go!!! glad that worked 😄. 

As for the character window issue, I suggest removing any unnecessary plugins you have and running the game. If that doesn't work try updating your ```.zipmod``` files with KKmanager and removing any mods you may have downloaded that could have also caused an error.

I'll close this issue since everything seems resolved, peace ✌😎.

**Closed by Prolo1** 2024-06-20 23:01 UTC
Labels: KK
