### ISSUE TITLE
CharaMorpher makes it so you can't find clothing bones in ABMX

### ISSUE THREAD

**Issue by ShnowOwl** [Prolo1/Character-Morpher#23] opened 2024-11-19 15:28 UTC
When I load a card, clothing bones can't be found in ABMX. Works on base Chika but not on any loaded card, wether it has been morphed in the past or not. First image with plugin, 2nd without.
![WithPlugin](https://github.com/user-attachments/assets/46e6f614-81cd-4829-8f24-32ce527aa28b)
![WithoutPlugin](https://github.com/user-attachments/assets/029dc008-af1b-4e20-991a-e302857dbf38)

**Comment by Prolo1** [comment] 2024-11-21 04:01
I'll see if I can fix that, thanks for letting me know. 
For my own reference, what versions of Character Morpher and ABMX are you using? 
Also, send me the card this is happening with so I can make sure this happens on my end too.

**Comment by ShnowOwl** [comment] 2024-11-21 11:00
ABMX 5.0.5.0, CharaMorph 1.2.1.7. I had an older version before and it happened on that one too though.
It doesn't really matter what card I use, it happens on every single one, even cards that aren't mine. Except on base Chika, of course. 
Here's a random one I guess: https://files.catbox.moe/wu13eb.zip
Put any clothes with bones on her and search for them.

**Comment by Prolo1** [comment] 2024-11-21 20:31
Sorry if I wasn't clear, but I meant the clothing card you had an issue with. I don't have many clothing cards with bones (too many character cards), and if I do I have no idea which ones. It helps make sure your exact issue is mine.

**Comment by ShnowOwl** [comment] 2024-11-21 22:16
Ah, my bad. While testing it out, it seems that loading the coordinate helps with not finding the bones though... I only get the error when I load a card or switch to the clothing with the bones manually, not when I load it via a coordinate. So I suggest you try that (search for "Evening" in Tops, like in my example).
Coordinate+Mod required: https://files.catbox.moe/82zl71.zip

**Comment by Prolo1** [comment] 2024-11-22 11:41
thanks for the coordinate+mod👍. Also, for that little piece of info. It should help with figuring this out a bit quicker. I'll do this when I have a solid section of time, so stay tuned.

**Comment by Prolo1** [comment] 2024-11-24 23:19
I've tested out your issue, but I can also confirm that this happens without my mod as well (I removed it completely)... so the problem is with ABMX in general. It could also be another mod that manipulates bones, but I highly doubt that (since I don't think I have any). Is there any other reason you think it's my mod? If not, then I'll just close this issue.

[just confirmation] 
![image](https://github.com/user-attachments/assets/b8539232-4b10-42c2-a0f4-b0ac1f0e519f)

**Comment by Prolo1** [comment] 2024-11-24 23:29
If I had to guess, ABMX just forgot to refresh bones in the advanced window or update bone lists unless they come from the model itself or coordinate card.

EDIT:
like I suspected, if you change the Uncensor Selector setting to anything you can find the bones again
![image](https://github.com/user-attachments/assets/f33de172-b01e-4d93-820d-717705d7b0e9)

**Comment by ShnowOwl** [comment] 2024-11-25 00:33
The reason I thought it was this plugin was that I tried removing plugins until it fixed the issue and removing the CharaMorph plugin seemed to fix the issue. Strange.. Good to know how to fix it at least, thanks!

**Comment by Prolo1** [comment] 2024-11-25 03:58
no prob let me know if you find any other issues

**Closed as completed by Prolo1** 2024-11-25 03:58 UTC
